### ISSUE TITLE
No bin file directory

### ISSUE THREAD

**Issue by GeorginaBenson** [phillipstanleymarbell/sunflower-simulator#17]
In tools there shoud be a tools/bin directory - I have fololwed all the steps up to this point, but have not got a tools/bin directory to add to my path

**Comment by phillipstanleymarbell** [comment]
`tools/bin` is created when you build the cross-compiler (described in the README.md, step 4)

**Comment by GeorginaBenson** [comment]
Sorry I was being stupid - I forgot to run make once downloading all the tools/source things.
