### ISSUE TITLE
Consider using `clang-format`

### ISSUE THREAD

**Issue by phillipstanleymarbell** [phillipstanleymarbell/sunflower-simulator#25]

**Comment by harrysarson** [comment]
The options for clang format are described here: https://clang.llvm.org/docs/ClangFormatStyleOptions.html#configurable-format-style-options

The choices are:

<ul class="last simple">
<li><code class="docutils literal notranslate"><span class="pre">LLVM</span></code>
A style complying with the <a class="reference external" href="https://llvm.org/docs/CodingStandards.html">LLVM coding standards</a></li>
<li><code class="docutils literal notranslate"><span class="pre">Google</span></code>
A style complying with <a class="reference external" href="http://google-styleguide.googlecode.com/svn/trunk/cppguide.xml">Google’s C++ style guide</a></li>
<li><code class="docutils literal notranslate"><span class="pre">Chromium</span></code>
A style complying with <a class="reference external" href="https://www.chromium.org/developers/coding-style">Chromium’s style guide</a></li>
<li><code class="docutils literal notranslate"><span class="pre">Mozilla</span></code>
A style complying with <a class="reference external" href="https://developer.mozilla.org/en-US/docs/Developer_Guide/Coding_Style">Mozilla’s style guide</a></li>
<li><code class="docutils literal notranslate"><span class="pre">WebKit</span></code>
A style complying with <a class="reference external" href="https://www.webkit.org/coding/coding-style.html">WebKit’s style guide</a></li>
</ul>

Any preference?

**Comment by phillipstanleymarbell** [comment]
I'm not excited about any of the choices. Let's discuss it in person to find a least-disliked option. Thanks for picking this up and for the Travis integration!

**Comment by harrysarson** [comment]
clang-format is almost infinitely configurable so formatting rules that match the coding style guidelines could be created. However, creating custom rules would be quite a lot of work I think and this would be another file that must be maintained. Definitely lets discuss in person :+1:

**Comment by harrysarson** [comment]
We decided to hold off on formatting for now.
