### ISSUE TITLE
32 bit float opperations do not check that arguments are "NaN boxed" when stored in 64 bit registers.

### ISSUE THREAD

**Issue by harrysarson** [phillipstanleymarbell/sunflower-simulator#54]
**Describe the bug**

When we store single precision (32 bit) floating point values in 64 bit floating point registers they should be `NaN` boxed: the first 32 bits should be set to 1. Currently this does not happen, instead single precision floating point values are zero extended.

**To Reproduce**
Run `riscv_newton-raphson` benchmark and inspect the values of the floating point registers.

_Note: currently inspecting these registers requires modification of sunflower source code._

**Expected behavior**
As described in section 9.2 of https://riscv.org/specifications/:

> When multiple floating-point precisions are supported, then valid values of narrower n-bit types,
n < FLEN, are represented in the lower n bits of an FLEN-bit NaN value, in a process termed
NaN-boxing. The upper bits of a valid NaN-boxed value must be all 1s. Valid NaN-boxed n-bit
values therefore appear as negative quiet NaNs (qNaNs) when viewed as any wider m-bit value,
n < m ≤ FLEN.

**Host OS:**
 - OS: Linux (Ubuntu 18)

**You local changes (please complete the following information):**
````
origin	https://github.com/phillipstanleymarbell/sunflower-simulator (fetch)
origin	https://github.com/phillipstanleymarbell/sunflower-simulator (push)
```

**Comment by harrysarson** [comment]
Sorry, the original ticket is wrong. Currently sunflower converts

```
single precision floats -> 32 bit unsigned integers -> 64 bit unsigned integers
```

which are stored. This has the effect of zero filling single precision floats. This is still wrong as floats should be 1 filled. I have updated the issue accordingly.

**Comment by phillipstanleymarbell** [comment]
Thanks for raising this @harrysarson. Passing to @rjlv2, who is the owner of the RV32FD implementation.

**Comment by harrysarson** [comment]
Sunflower now does these bits:

> Floating-point n-bit transfer operations move external values held in IEEE standard formats into
and out of the f registers, and comprise floating-point loads and stores (FLn/FSn) and floating-
point move instructions (FMV.n.X/FMV.X.n). A narrower n-bit transfer, n < FLEN, into the f
registers will create a valid NaN-boxed value by setting all upper FLEN−n bits of the destination
f register to 1. A narrower n-bit transfer out of the floating-point registers will transfer the lower
n bits of the register ignoring the upper FLEN−n bits.

> Conversions from integer to floating-point (e.g., FCVT.S.X), will NaN-box any results narrower
than FLEN to fill the FLEN-bit destination register

But **not** these bits:

> Floating-point compute and sign-injection operations calculate results based on the FLEN-bit values
held in the f registers. A narrow n-bit operation, where n < FLEN, checks that input operands
are correctly NaN-boxed, i.e., all upper FLEN−n bits are 1. If so, the n least-significant bits of the
input are used as the input value, otherwise the input value is treated as an n-bit canonical NaN.
An n-bit floating-point result is written to the n least-significant bits of the destination f register,
with all 1s written to the uppermost FLEN−n bits to yield a legal NaN-boxed value.

> Conversions from narrower n-bit floating-
point values to integer (e.g., FCVT.X.S) will check for legal NaN-boxing and treat the input as the
n-bit canonical NaN if not a legal n-bit value.

If values start correctly nan boxed sunflower will now keep them that way. However, sunflower does not correctly handle non correctly nan boxed floats. (An example that would currently behave in a non conforming way is `fmv.s fa0, fa0` when `fa0` stores a double precision value).

**Comment by rjlv2** [comment]
I've added a function to check if the operands are NaN-boxed.

**Comment by harrysarson** [comment]
In this case I believe this can be closed!
