### ISSUE TITLE
Dump floating point registers in riscv

### ISSUE THREAD

**Issue by harrysarson** [phillipstanleymarbell/sunflower-simulator#57]
There is currently no way to view the contents of floating point registers when running sunflower in "riscv" mode.

I have two possible ideas about a solution although there may be other (better) approaches.
1) Add a new command that dumps floating point registers.
2) Modify the behavior of the existing command `DUMPREGS` to also print the values stored in floating point registers.

**Comment by harrysarson** [comment]
cc: @rjlv2

**Comment by phillipstanleymarbell** [comment]
@SFeng94's implementation of RV32F in sunflower has a modification of dumpers that I much like: https://github.com/SFeng94/sunflower-simulator. You could nudge him to contribute his deltas as a pull request.

**Comment by harrysarson** [comment]
@SFeng94's implementation looks great! It would be great to print both the single and double precision interpretation of the value stored in the register though[[1]](1). Additionally, @rjlv2 has added 64 bit floating point registers so some tweaks would be required (https://github.com/SFeng94/sunflower-simulator/commit/51aa638be8aad5cf661b7db173dcaeac77c39bc4#diff-4ccad4a859a8dfa327db7721cefc246a only displays 32 bits).

[1]: I may be biased as I am working on an extension that uses single precision floating point values.

**Comment by rjlv2** [comment]
I've modified the implementation of `riscvdumpregs` to print the bits and also floating/double values. I also included functions `mbit64print` to print out 64-bit values. A function `mfloatprint` checks if the value is NaN-boxed and prints out either a floating point or double value.

![image](https://user-images.githubusercontent.com/16257373/53408309-12938680-39b6-11e9-956e-b171749c31e7.png)

**Comment by harrysarson** [comment]
Is printing the bits worth it? There are a lot of them and they don't give much information.

Maybe just printing the hexadecimal version would be more concise

**Comment by harrysarson** [comment]
I like it through :)

**Comment by phillipstanleymarbell** [comment]
I like it.
