### ISSUE TITLE
Show ABI names when dumping registers

### ISSUE THREAD

**Issue by harrysarson** [phillipstanleymarbell/sunflower-simulator#63]
**Is your feature request related to a problem?**

When dumping registers it is hard to find the significant registers.

**Describe the solution you'd like**

If sunflower print the ABI name of a register (`sp` for register 2, `ra` for 3, etc) it would be much easier to interpret the register dump.

**Additional context**

If this feature is wanted I can submit a PR.

**Comment by phillipstanleymarbell** [comment]
Yes.
