### ISSUE TITLE
Incorrect evaluation of double precision floating point operations

### ISSUE THREAD

**Issue by harrysarson** [phillipstanleymarbell/sunflower-simulator#73]
**Describe the bug**

Sunflower gives the wrong value for the double precision inverse sine. Assuming newlib's implementation of `asin()` is correct one of the double precision floating point instructions it uses must be incorrect.

**To Reproduce**

```asm
.globl _start
.globl __errno
.align	4

_start:
init:
.option push
.option norelax
	la		gp, __global_pointer$
.option pop
	call	bug;
	call 	exit;

__errno:
	.long	0

.fp_s_5:
  .word 1056964608

.fp_d_5:
  .word 0
  .word 1071644672

bug:
	li          5, 7;
	lu         a5, %hi(.fp_d_5);
	fld        fa0, %lo(.fp_d_5)(a5);
	fmv.d   fs2, fa0;
	call 	    asin;
	fmv.d   fs0, fa0;

	ret;
```

**Expected behavior**

Value of `0.52` (rad) stored in _fs0_.

**Actual behaviour**

Value of `-0.42482576` stored in _fs0_. 

**Screenshots**

![Screenshot from 2019-03-13 16-24-23](https://user-images.githubusercontent.com/16308754/54296271-7d46e380-45ac-11e9-99f9-e293e475e6da.png)

cc: @rjlv2 

---

Note this is running on a patched version of sunflower - but I have not touched anything that could have caused this (I hope).

**Comment by rjlv2** [comment]
Was the assembly file you showed generated by gcc? I tried compiling a program that uses `asin()` and it seems to work. I used a slightly older version which still prints out bits instead of hex. I tested on asin(1), which gave 0.5*pi approximately equal to 1.570796.

![image](https://user-images.githubusercontent.com/16257373/54323209-1d722c00-45f0-11e9-9240-15974a8abafb.png)

**Comment by harrysarson** [comment]
Found it! #74 

---

To confirm `asin(1)` was giving the correct answer, `asin(0.5)` wasn't. The implementation of `asin(1)` must not divide anything whereas the implementation of `asin(1)` does.
